name: face-id-matching
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.11.12=h4c7d964_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - liblzma=5.8.1=h2466b09_2
  - libsqlite=3.51.1=hf5d6505_1
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.6.0=h725018a_0
  - pip=25.3=pyh8b19718_0
  - python=3.11.14=h0159041_2_cpython
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h2c6b04d_3
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - facenet-pytorch==2.6.0
      - filelock==3.20.1
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - narwhals==2.14.0
      - networkx==3.6.1
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.3.3
      - pillow==10.2.0
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - six==1.17.0
      - smmap==5.0.2
      - streamlit==1.52.2
      - sympy==1.14.0
      - tenacity==9.1.2
      - toml==0.10.2
      - torch==2.2.2
      - torchvision==0.17.2
      - tornado==6.5.4
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - watchdog==6.0.0
prefix: face-id-matching
